version: "3.9"

services:
  api:
    build:
      context: ./apps/api
    env_file:
      - .env.example
    volumes:
      - ./apps/api/app:/app/app
      - ./data:/app/data
      - ./uploads:/app/uploads
    ports:
      - "8000:8000"

  web:
    build:
      context: ./apps/web
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    volumes:
      - ./apps/web:/app
    ports:
      - "3000:3000"
    depends_on:
      - api
